const scenes=[{k:{es:'Ciudad de México · Casa de ediciones',en:'Mexico City · House of editions'},t:{es:['Encuentra','tu verdad'],en:['Find','your truth']},n:{es:'Tés de edición limitada. Una temporada. Una historia. Una verdad que no vuelve a repetirse.',en:'Limited-edition teas. One season. One story. One truth that never returns in the same form.'}},{k:{es:'El ritual',en:'The ritual'},t:{es:['Una pausa.','Una verdad.'],en:['A pause.','A truth.']},n:{es:'Cada etiqueta guarda una frase creada para la edición que tienes en las manos.',en:'Every tag carries a line created for the edition in your hands.'}},{k:{es:'Hecho para compartir',en:'Made to be shared'},t:{es:['Dos tazas.','Un momento.'],en:['Two cups.','One moment.']},n:{es:'Lujo sin ruido. Té, conversación y una Ciudad de México que cambia con la luz.',en:'Luxury without noise. Tea, conversation and a Mexico City that changes with the light.'}},{k:{es:'Edición 01 · Cosecha',en:'Edition 01 · Harvest'},t:{es:['Nada aquí','es permanente.'],en:['Nothing here','is permanent.']},n:{es:'Una edición aparece una vez, vive una temporada y después se retira.',en:'An edition appears once, lives for a season, and then retires.'}},{k:{es:'La verdad de hoy',en:'Today’s truth'},t:{es:['Baja el ruido.','Escucha.'],en:['Lower the noise.','Listen.']},n:{es:'La etiqueta no adorna la taza. Termina el ritual.',en:'The tag does not decorate the cup. It completes the ritual.'}},{k:{es:'Próxima edición · Otoño 2026',en:'Next edition · Autumn 2026'},t:{es:['Cosecha','no volverá igual.'],en:['Harvest','will not return the same.']},n:{es:'Entra a la lista para conocer la primera edición antes de que salga al mundo.',en:'Join the list to meet the first edition before it enters the world.'}}];
const truths=[{es:'La verdad no siempre grita. A veces espera a que estés en silencio.',en:'Truth does not always shout. Sometimes it waits for you to become quiet.'},{es:'Lo que cuidas en privado también define quién eres.',en:'What you protect in private also defines who you are.'},{es:'No todo lo que termina estaba destinado a fracasar.',en:'Not everything that ends was meant to fail.'},{es:'Tu paz también es una forma de poder.',en:'Your peace is also a form of power.'},{es:'Hay respuestas que llegan cuando dejas de perseguirlas.',en:'Some answers arrive when you stop chasing them.'}];
let lang='es',active=0,q=0;const film=document.querySelector('.film'),layers=[...document.querySelectorAll('.layer')],copy=document.getElementById('filmcopy'),progress=document.getElementById('progress');progress.innerHTML=scenes.map(()=>'<i></i>').join('');
function renderFilm(){const s=scenes[active];copy.innerHTML=`<p class="kicker">${s.k[lang]}</p><h1>${s.t[lang][0]}<span>${s.t[lang][1]}</span></h1><p class="filmnote">${s.n[lang]}</p>`;[...progress.children].forEach((i,n)=>i.classList.toggle('on',n<=active));layers.forEach((l,n)=>{l.classList.toggle('active',n===active);const v=l.querySelector('video');if(v){if(n===active)v.play().catch(()=>{});else v.pause()}})}
function onScroll(){const r=film.getBoundingClientRect(),travel=Math.max(1,film.offsetHeight-innerHeight),p=Math.min(1,Math.max(0,-r.top/travel)),next=Math.min(scenes.length-1,Math.floor(p*scenes.length));if(next!==active){active=next;renderFilm()}}
addEventListener('scroll',()=>requestAnimationFrame(onScroll),{passive:true});addEventListener('resize',onScroll);renderFilm();
function renderTruth(){document.getElementById('quote').textContent='“'+truths[q][lang]+'”';document.getElementById('truthmeta').textContent='TECITO · VERDAD '+String(q+1).padStart(3,'0')}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-es][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.getElementById('lang').textContent=lang==='es'?'EN':'ES';document.getElementById('email').placeholder=lang==='es'?'Tu correo':'Your email';renderFilm();renderTruth()}
document.getElementById('lang').onclick=()=>{lang=lang==='es'?'en':'es';translate()};document.getElementById('truthbtn').onclick=()=>{q=(q+1)%truths.length;renderTruth()};renderTruth();document.getElementById('form').onsubmit=e=>{e.preventDefault();document.getElementById('formmsg').textContent=lang==='es'?'Solicitud registrada en esta vista previa.':'Request registered in this preview.';e.target.reset()};
